import { StyleSheet } from 'react-native';
import { solarTheme } from '../theme/solarTheme';

export const webStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: solarTheme.background.main,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: solarTheme.text.primary,
  },
  subtitle: {
    fontSize: 16,
    color: solarTheme.text.secondary,
    marginTop: 4,
  },
  weatherInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 16,
  },
  locationText: {
    color: solarTheme.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  weatherMetrics: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  weatherMetric: {
    alignItems: 'center',
  },
  weatherMetricValue: {
    color: solarTheme.text.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  weatherMetricLabel: {
    color: solarTheme.text.secondary,
    fontSize: 12,
    marginTop: 2,
  },
  weatherIcon: {
    fontSize: 32,
  },
  mainContent: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 20,
    gap: 10,
    height: '100%',
  },
  chartContainer: {
    flex: 1.4,
    backgroundColor: solarTheme.background.card,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    overflow: 'hidden',
    height: '100%',
  },
  chartWrapper: {
    flex: 1,
    minHeight: 500,
    maxHeight: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    paddingBottom: 0,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  chartTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: solarTheme.text.primary,
  },
  chartSubtitle: {
    fontSize: 14,
    color: solarTheme.text.secondary,
    marginTop: 4,
  },
  sidePanel: {
    flex: 2,
    gap: 12,
    minWidth: 320,
    maxWidth: 480,
    height: '100%',
    overflow: 'hidden',
  },
  metricCard: {
    backgroundColor: solarTheme.background.card,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  metricIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  metricValue: {
    fontSize: 24,
    fontWeight: '700',
    color: solarTheme.text.primary,
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 12,
    color: solarTheme.text.secondary,
    textAlign: 'center',
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 20,
  },
  controlsCard: {
    backgroundColor: solarTheme.background.card,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    flex: 1,
    minHeight: 0,
  },
  controlsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: solarTheme.text.primary,
    marginBottom: 12,
  },
  quickDateButtons: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    justifyContent: 'space-between',
  },
  quickDateButton: {
    backgroundColor: solarTheme.background.cardLight,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickDateButtonActive: {
    backgroundColor: solarTheme.secondary.accent,
    borderColor: solarTheme.secondary.accent,
  },
  quickDateButtonText: {
    color: solarTheme.text.secondary,
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  quickDateButtonTextActive: {
    color: solarTheme.text.primary,
    fontWeight: '600',
  },
  dateDisplay: {
    backgroundColor: solarTheme.background.cardLight,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
  },
  dateText: {
    color: solarTheme.text.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  centeredDateText: {
    color: solarTheme.text.primary,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  controlButton: {
    backgroundColor: solarTheme.secondary.accent,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  controlButtonText: {
    color: solarTheme.text.primary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  dataSourceIndicator: {
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
  },
  dataSourceText: {
    color: solarTheme.text.accent,
    fontSize: 12,
    fontWeight: '500',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  compactWeatherMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
  },
  compactWeatherMetric: {
    alignItems: 'center',
    minWidth: '45%',
  },
  dataTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  dataTypeButton: {
    backgroundColor: solarTheme.background.cardLight,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    minWidth: '30%',
    maxWidth: '32%',
    minHeight: 55,
  },
  dataTypeButtonActive: {
    backgroundColor: solarTheme.secondary.accent,
    borderColor: solarTheme.secondary.accent,
  },
  dataTypeIcon: {
    fontSize: 18,
    marginBottom: 6,
  },
  dataTypeButtonText: {
    color: solarTheme.text.secondary,
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
  dataTypeButtonTextActive: {
    color: solarTheme.text.primary,
    fontWeight: '600',
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 4,
  },
  legendCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    color: solarTheme.text.secondary,
    fontSize: 12,
    fontWeight: '500',
  },
});

export const mobileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: solarTheme.background.main,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 30, // Increased from 20 to add more space
    alignItems: 'center',
    backgroundColor: solarTheme.background.main, // Ensure it has background
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: solarTheme.text.primary,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: solarTheme.text.secondary,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 20,
  },
  chartContainer: {
    backgroundColor: solarTheme.background.card,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    marginBottom: 20,
    overflow: 'hidden', // Ensure chart doesn't overflow container
  },
  chartWrapper: {
    flex: 1,
    minHeight: 250, // Slightly smaller minimum height for mobile
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: solarTheme.text.primary,
  },
  chartSubtitle: {
    fontSize: 14,
    color: solarTheme.text.secondary,
    marginTop: 4,
  },
  metricCard: {
    flex: 1,
    backgroundColor: solarTheme.background.card,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  metricIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '700',
    color: solarTheme.text.primary,
    marginBottom: 2,
  },
  metricLabel: {
    fontSize: 10,
    color: solarTheme.text.secondary,
    textAlign: 'center',
  },
  controlsCard: {
    backgroundColor: solarTheme.background.card,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  controlsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: solarTheme.text.primary,
    marginBottom: 16,
  },
  quickDateButtons: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
    justifyContent: 'space-between',
  },
  quickDateButton: {
    backgroundColor: solarTheme.background.cardLight,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickDateButtonActive: {
    backgroundColor: solarTheme.secondary.accent,
    borderColor: solarTheme.secondary.accent,
  },
  quickDateButtonText: {
    color: solarTheme.text.secondary,
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
  quickDateButtonTextActive: {
    color: solarTheme.text.primary,
    fontWeight: '600',
  },
  dateDisplay: {
    backgroundColor: solarTheme.background.cardLight,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
  },
  dateText: {
    color: solarTheme.text.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  centeredDateText: {
    color: solarTheme.text.primary,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  controlButton: {
    backgroundColor: solarTheme.secondary.accent,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  controlButtonText: {
    color: solarTheme.text.primary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  // Desktop-only styles for mobile fallback
  weatherInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20, // Add space below
    gap: 16,
  },
  locationText: {
    color: solarTheme.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  weatherMetrics: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  weatherMetric: {
    alignItems: 'center',
  },
  weatherMetricValue: {
    color: solarTheme.text.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  weatherMetricLabel: {
    color: solarTheme.text.secondary,
    fontSize: 12,
    marginTop: 2,
  },
  weatherIcon: {
    fontSize: 32,
  },
  weatherText: {
    color: solarTheme.text.primary,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  mainContent: {
    flex: 1,
    flexDirection: 'column',
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  sidePanel: {
    gap: 24,
  },
  dataSourceIndicator: {
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
  },
  dataSourceText: {
    color: solarTheme.text.accent,
    fontSize: 12,
    fontWeight: '500',
  },
  compactWeatherMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
  },
  compactWeatherMetric: {
    alignItems: 'center',
    minWidth: '45%',
  },
  dataTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginHorizontal: 0,
  },
  dataTypeButton: {
    backgroundColor: solarTheme.background.cardLight,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(79, 211, 204, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    width: '31%', // 3 per row with spacing
    minHeight: 60,
    marginBottom: 6,
    marginHorizontal: 2,
  },
  dataTypeButtonActive: {
    backgroundColor: solarTheme.secondary.accent,
    borderColor: solarTheme.secondary.accent,
  },
  dataTypeIcon: {
    fontSize: 16,
    marginBottom: 4,
  },
  dataTypeButtonText: {
    color: solarTheme.text.secondary,
    fontSize: 10,
    fontWeight: '500',
    textAlign: 'center',
  },
  dataTypeButtonTextActive: {
    color: solarTheme.text.primary,
    fontWeight: '600',
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 4,
  },
  legendCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    color: solarTheme.text.secondary,
    fontSize: 12,
    fontWeight: '500',
  },
});
